#!/bin/sh

home=$HOME
cwd=$(pwd)
plugm=$home/.vim/autoload/plug.vim

# powerline-fonts
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts && ./install.sh && cd .. && rm -rf fonts

if [ ! -f $plugm ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -f $plugm ]; then
    sudo cp ./plug.vim $plugm
fi

ln -sf $cwd/_agignore $home/.agignore
ln -sf $cwd/_vimrc $home/.vimrc

vim -c "PlugInstall" +"qall"

exit 0
